apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-chart.fullname" . }}-secret
  labels:
    {{- include "django-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.secrets }}
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
