controller:
  serviceAccount:
    create: true
    name: "jenkins"
    annotations: 
      eks.amazonaws.com/role-arn: "${aws_iam_role.jenkins_irsa_role.arn}"
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: "2.479.3-jdk17"
  initializeOnce: true
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1536Mi"
    requests:
      cpu: "250m"
      memory: "1024Mi"



  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - github

persistence:
  enabled: true
  storageClass: gp2
  size: 10Gi