image:
  repository: 801867401886.dkr.ecr.eu-west-2.amazonaws.com/final-project
  tag: build-18
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  DEBUG: "False"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

secrets:
  POSTGRES_PASSWORD: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

# livenessProbe:
#   httpGet:
#     path: /
#     port: 8000
#   initialDelaySeconds: 30
#   periodSeconds: 10

# readinessProbe:
#   httpGet:
#     path: /
#     port: 8000
#   initialDelaySeconds: 10
#   periodSeconds: 5
